# configuration to run via tox

[tox]
envlist = py311-sphinx9

[testenv]
usedevelop = true

[testenv:py{311,312,313,314}-sphinx{8,9}]
description = Run pytest
deps =
    sphinx8: sphinx>=8,<9
    sphinx9: sphinx>=9,<10
extras = testing
commands = pytest {posargs}

[testenv:docs-{update,clean}]
description = Build the documentation
extras = docs
allowlist_externals =
    echo
    rm
passenv =
    BUILDER
    TERM
commands =
    clean: rm -rf docs/_build/{env:BUILDER:html}
    sphinx-build -nW --keep-going -b {env:BUILDER:html} {posargs} docs/ docs/_build/{env:BUILDER:html}
commands_post = echo "open file://{toxinidir}/docs/_build/html/index.html"
